version: "3"
services:
    db-test:
        image: postgres
        container_name: db-test
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL_TEST}
        ports:
            - "5432:5432"
        networks:
            - puma-network
    project-service-test:
        container_name: project-service-test
        environment:
            ENVIRONMENT: test
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - db-test
        volumes:
            - ./:/app
            - /app/node_modules
        command:
            ["./wait-for-it.sh", "db:5432", "--", "npm","run","start"]
        networks:
            - puma-network
          
networks:
    puma-network:            
